/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest17({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/boxTest1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Box_Comp.geometry} material={materials.Mat_Box_Comp} position={[0.44, 0, 1.46]} />
    </group>
  )
}

useGLTF.preload('/boxTest1.gltf')
