/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest1({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/dossiCharTest1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.GumJee_Comp.geometry} material={materials.Mat_GumJee_Comp} position={[-8.84, 0, 5.76]} />
    </group>
  )
}

useGLTF.preload('/dossiCharTest1.gltf')
