/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/grenadeTest1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Grenade_Normal_Comp.geometry}
        material={materials.Mat_Grenade_Normal_Comp}
        position={[-2.05, 0.02, 5.76]}
      />
    </group>
  )
}

useGLTF.preload('/grenadeTest1.gltf')
