/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest5({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/penseTest1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Bridge_Fence_Comp.geometry}
        material={materials.Mat_Bridge_Fence_Comp}
        position={[25.01, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/penseTest1.gltf')
