/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest7({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rifleTest1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Rifle_Comp.geometry} material={materials.Mat_Rifle_Comp} position={[-1.15, 0.02, 5.76]} />
    </group>
  )
}

useGLTF.preload('/rifleTest1.gltf')
