/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest13({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wallTest2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Wall_Outer_Edge_Comp.geometry}
        material={materials.Mat_Wall_Outer_Edge_Comp}
        position={[15.82, 0, 7.8]}
      />
    </group>
  )
}

useGLTF.preload('/wallTest2.gltf')
