/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest14({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/wallTest2Type1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Wall_Straight_Door_2Tile_Comp.geometry}
        material={materials.Mat_Wall_Straight_Door_2Tile_Comp}
        position={[0, -0.06, -5.75]}
      />
    </group>
  )
}

useGLTF.preload('/wallTest2Type1.gltf')
