/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest4({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/objTest2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Bridge_Structure_Comp.geometry}
        material={materials.Mat_Bridge_Structure_Comp}
        position={[21.48, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/objTest2.gltf')
