/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest9({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/stoneTest1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Rock_Type01_Comp.geometry}
        material={materials.Mat_Rock_Type01_Comp}
        position={[27.05, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/stoneTest1.gltf')
