/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ModelTest16({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/waterTest1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Tile_Water_Comp.geometry}
        material={materials.Mat_Tile_Water_Comp}
        position={[3.71, 0, -1.37]}
      />
    </group>
  )
}

useGLTF.preload('/waterTest1.gltf')
